version: '3.8'

services:
  localstack:
    image: localstack/localstack:0.14.2
    ports:
      - "4566:4566"
      - "8000:8000"
    environment:
      - SERVICES=dynamodb,sqs
      - DEFAULT_REGION=us-east-1
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
