# --- Perfil ---
spring.profiles.active=test-integration

# --- Valores para placeholders ---
aws.region=us-east-1
app.dynamodb.validation.enabled=false

# --- Propiedades para LocalStack ---
# Estos valores serán sobrescritos por @DynamicPropertySource
dynamodb.endpoint=http://localhost:4566
dynamodb.region=us-east-1

cloud.aws.endpoint=http://localhost:4566

# SQS (se configurará dinámicamente)
aws.sqs.queue.url=http://localhost:4566/000000000000/patient-queue-test

# --- Logging ---
logging.level.com.colombia.eps=DEBUG
logging.level.software.amazon.awssdk=INFO
logging.level.org.testcontainers=INFO
logging.level.com.github.dockerjava=INFO

spring.main.allow-bean-definition-overriding=true
spring.graphql.graphiql.enabled=true

aws.session.name=test-session
alias=${ALIAS}
password=${PASSWORD}
certificate.name=${CERTIFICATE_NAME}
privateKey.password=${PRIVATEKEY_PASSWORD}
cognito.user.pool.id=us-east-1_TEST123
cognito.patient.group=Patients