# DynamoDB Local Configuration
aws.dynamodb.endpoint=http://localhost:8000
aws.dynamodb.access-key=dummy
aws.dynamodb.secret-key=dummy

# SQS Local Configuration
aws.sqs.queue.url=http://localhost:4566/000000000000/patient-queue

# Application Configuration
logging.level.com.colombia.eps=DEBUG