
# AWS DynamoDB Configuration (uses environment variables)
aws.dynamodb.access-key=${AKI_DYNAMO_USER}
aws.dynamodb.secret-key=${SAK_DYNAMO_USER}
aws.dynamodb.role=${DYNAMO_ROL}
app.dynamodb.validation.enabled=true

# AWS Cognito Configuration (uses environment variables)
aws.cognito.role=${COGNITO_ROL}
aws.cognito.access-key=${AKI_COGNITO_USER}
aws.cognito.secret-key=${SAK_COGNITO_USER}

# AWS Ses Configuration (uses environment variables)
aws.ses.role=${SES_ROL}
aws.ses.access-key=${AKI_SES_USER}
aws.ses.secret-key=${SAK_SES_USER}

#AWS sqs Configuration (uses environment variables)
aws.sqs.queue.url=${SQS_QUEUE_URL}
aws.sqs.access-key=${AKI_SQS_USER}
aws.sqs.secret-key=${SAK_SQS_USER}
aws.sqs.role=${SQS_ROL}

# Application Configuration
logging.level.com.colombia.eps=INFO
cognito.user.pool.id=${USER_POOL_ID}
cognito.patient.group=${PATIENT_GROUP}