
aws.session-name=${PATIENT_SESSION_NAME}
# AWS DynamoDB Configuration (uses environment variables)
aws.dynamodb.access-key=${AKI_DYNAMO_USER}
aws.dynamodb.secret-key=${SAK_DYNAMO_USER}
aws.dynamodb.role=${DYNAMO_ROL}

# AWS Cognito Configuration (uses environment variables)
aws.cognito.role=${COGNITO_ROL}
aws.cognito.access-key=${AKI_COGNITO_USER}
aws.cognito.secret-key=${SAK_COGNITO_USER}

# AWS Ses Configuration (uses environment variables)
aws.ses.role=${SES_ROL}
aws.ses.access-key=${AKI_SES_USER}
aws.ses.secret-key=${SAK_SES_USER}
# Application Configuration
logging.level.com.colombia.eps=INFO