package com.colombia.eps.patient.infrastructure.helper;

public enum ExceptionName {
    PATIENT_NOT_FOUND,
    PATIENT_ALREADY_EXISTS,
    CREATE_SES_IDENTITY,
    IDENTITY_NOT_FOUND,
    PATIENT_ALREADY_EXIST,
    GET_VERIFICATION_STATUS_IN_SES,
    GET_PATIENT,
    CHANGE_PATIENT_STATUS,
    SAVE_PHOTO_TO_PATIENT,
    UPDATE_PATIENT,
    CREATE_USER_IN_USER_POOL,
    ADD_USER_TO_GROUP,
}